Appventas/urls.py
from Appventas import views
from django.urls import path


urlpatterns = [
    path('inicio/', views.inicio, name='inicio'),
    path('about', views.about, name='about'),

    path('clientes/', views.clienteslistview.as_view(), name='listaclientes'),
    path('clientes/nuevo', views.clientescreateview.as_view(), name='nuevocliente'),
    path('clientes/<pk>', views.clientesdetalle.as_view(), name='clientesdetalle'),
    path('clientes/<pk>/editar', views.clientesupdateview.as_view(), name='clienteseditar'),
    path('clientes/<pk>/borrar', views.clientesdeleteview.as_view(), name="clientesborrar"),

    path('productos/', views.productoslistview.as_view(), name='listaproductos'),
    path('productos/nuevo', views.productoscreateview.as_view(), name='nuevoproducto'),
    path('productos/<pk>', views.productosdetalle.as_view(), name='productosdetalle'),
    path('productos/<pk>/editar', views.productosupdateview.as_view(), name='productoseditar'),
    path('productos/<pk>/borrar', views.productosdeleteview.as_view(), name="productosborrar"),
    
    path('servicios/', views.servicioslistview.as_view(), name='listaservicios'),
    path('servicios/nuevo', views.servicioscreateview.as_view(), name='nuevoservicio'),
    path('servicios/<pk>', views.serviciosdetalle.as_view(), name='serviciosdetalle'),
    path('servicios/<pk>/editar', views.serviciosupdateview.as_view(), name='servicioseditar'),
    path('servicios/<pk>/borrar', views.serviciosdeleteview.as_view(), name="serviciosborrar"),

    # path('busquedaproductos/', views.busquedaproductos, name='busquedaproductos'),
    # path('buscar/', views.buscar, name='buscar'),
]

Entrega3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Appventas/', include('Appventas.urls')),
    path('users/', include('users.urls')),
]

proyecto3/proyecto3/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from users import views
from django.contrib.auth.views import LogoutView
from .views import custom_logout
from .views import edit_profile
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('login/', views.login_request, name="Login"),
    path('register/', views.register, name="Register"),
    path('logout/', custom_logout, name="Logout"),
    path('profile/edit/', edit_profile, name='edit_profile'),
    path('password-change/', PasswordChangeView.as_view(template_name='users/cambiar_contrasena.html', success_url='/users/password-change-done/'), name='password_change'),
    path('password-change-done/', PasswordChangeDoneView.as_view(template_name='users/cambiar_contrasena_done.html'), name='password_change_done'),
]

Appventas/models.py
from django.db import models

class Clientes(models.Model):
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    
    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

class Productos(models.Model):
    producto = models.CharField(max_length=30)
    marca = models.CharField(max_length=30)
    precio = models.IntegerField()

    def __str__(self):
        return f"{self.producto} - {self.marca}"
    
    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

class Servicios(models.Model):
    servicio = models.CharField(max_length=30)
    precio = models.IntegerField()
    proveedor = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.servicio} - {self.proveedor}"
    
    class Meta:
        verbose_name = "Servicio"
        verbose_name_plural = "Servicios"

Appventas/forms.py
from django import forms

class ClientesFormulario(forms.Form):
    nombre = forms.CharField(max_length=40)
    apellido = forms.CharField(max_length=40)
    direccion = forms.CharField(max_length=100)
    email = forms.EmailField()

class ProductosFormulario(forms.Form):
    producto = forms.CharField(max_length=30)
    marca = forms.CharField(max_length=30)
    precio = forms.IntegerField()

class ServiciosFormulario(forms.Form):
    servicio = forms.CharField(max_length=30)
    precio = forms.IntegerField()
    proveedor = forms.CharField(max_length=30)

Appventas/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
from Appventas.models import Clientes, Productos, Servicios
from Appventas.forms import ClientesFormulario, ProductosFormulario, ServiciosFormulario
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

def inicio(req):
    return render(req, 'appventas/padre.html')

def about(req):
    fecha_actual = datetime.now()
    return render(req, 'appventas/about.html', {'fecha_actual': fecha_actual})

@login_required
def clientes(req):
    return render(req, 'appventas/clientes.html')

@login_required
def productos(req):
    return render(req, 'appventas/productos.html')

@login_required
def servicios(req):
    return render(req, 'appventas/servicios.html')

class clienteslistview(LoginRequiredMixin, ListView):
    model = Clientes
    template_name = 'appventas/clientes.html'

class clientesdetalle(LoginRequiredMixin, DetailView):
    model = Clientes
    template_name = 'appventas/clientesdetalle.html'

class clientescreateview(LoginRequiredMixin, CreateView):
    model = Clientes
    template_name = 'appventas/clientesform.html'
    success_url = reverse_lazy('listaclientes')
    fields = ['nombre', 'apellido', 'direccion', 'email']

class clientesupdateview(LoginRequiredMixin, UpdateView):
    model = Clientes
    template_name = 'appventas/clientesedit.html'
    success_url = reverse_lazy('listaclientes')
    fields = ['nombre', 'apellido', 'direccion', 'email']

class clientesdeleteview(LoginRequiredMixin, DeleteView):
    model = Clientes
    template_name = 'appventas/clientesdelete.html'
    success_url = reverse_lazy('listaclientes')


class productoslistview(LoginRequiredMixin, ListView):
    model = Productos
    template_name = 'appventas/productos.html'

class productosdetalle(LoginRequiredMixin, DetailView):
    model = Productos
    template_name = 'appventas/productosdetalle.html'

class productoscreateview(LoginRequiredMixin, CreateView):
    model = Productos
    template_name = 'appventas/productosform.html'
    success_url = reverse_lazy('listaproductos')
    fields = ['producto', 'marca', 'precio']

class productosupdateview(LoginRequiredMixin, UpdateView):
    model = Productos
    template_name = 'appventas/productosedit.html'
    success_url = reverse_lazy('listaproductos')
    fields = ['producto', 'marca', 'precio']

class productosdeleteview(LoginRequiredMixin, DeleteView):
    model = Productos
    template_name = 'appventas/productosdelete.html'
    success_url = reverse_lazy('listaproductos')


class servicioslistview(LoginRequiredMixin, ListView):
    model = Servicios
    template_name = 'appventas/servicios.html'

class serviciosdetalle(LoginRequiredMixin, DetailView):
    model = Servicios
    template_name = 'appventas/serviciosdetalle.html'

class servicioscreateview(LoginRequiredMixin, CreateView):
    model = Servicios
    template_name = 'appventas/serviciosform.html'
    success_url = reverse_lazy('listaservicios')
    fields = ['servicio', 'precio', 'proveedor']

class serviciosupdateview(LoginRequiredMixin, UpdateView):
    model = Servicios
    template_name = 'appventas/serviciosedit.html'
    success_url = reverse_lazy('listaservicios')
    fields = ['servicio', 'precio', 'proveedor']

class serviciosdeleteview(LoginRequiredMixin, DeleteView):
    model = Servicios
    template_name = 'appventas/serviciosdelete.html'
    success_url = reverse_lazy('listaservicios')

# def busquedaproductos(req):
#     return render (req, 'appventas/busquedaproductos.html')

# def buscar(req):
#     if req.GET['producto']:
#         producto = req.GET['producto']
#         productos2 = Productos.objects.filter(producto__contains=producto)

#         return render(req, "appventas/busquedaproductos.html", {"productos2":productos2, "producto": producto})
    
#     else:
#         respuesta = "No se enviaron datos"
    
#     return render(req, "appventas/busquedaproductos.html", {"respuesta":respuesta})

Appventas/templates/appventas/busquedaproductos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  
    {% extends "appventas/padre.html" %}

    {% load static %}

    {% block contenidoQueCambia %}

    <div class="container px-lg-5">
        <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
            <div class="m-4 m-lg-5">    

<p>Ingrese el producto a buscar:</p>

<form action="{% url 'buscar' %}" method="GET">

    <input type="text" name="producto" id="producto">
    <input type="submit" value="Buscar">

</form>

{% if productos2 %}

<!--<p>Estamos buscando: {{producto}}</p>-->
{% for prod in productos2 %}
<p>Producto: {{prod.producto}}</p>
<p>Marca: {{prod.marca}}</p>

{% endfor %}

{% elif producto %}
    <p>No hay datos con esa descripción</p>

{% endif %}

</div>
</div>
</div>

    {% endblock %}

</body>
</html>

Appventas/templates/appventas/clientesdelete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Borrar Cliente</title>
</head>
<body>

    {% extends "appventas/padre.html" %}

    {% load static %}

    {% block contenidoQueCambia %}

    <div class="container px-lg-5">
        <div class="p-2 p-lg-3 bg-light rounded-3 text-center">
            <div class="m-2 m-lg-3">

                <h3>Usted está en la sección de clientes</h3>
                <h5>Borrar Cliente</h5>
                <div style="text-align: left;">
                <form action="" method="POST">
                    {% csrf_token %}
                    Está seguro que desea borrar el cliente {{object.nombre}} {{object.apellido}}?
                    
                    <input type="submit" value="Si, eliminar">

                </form>          
                
                <a href="{% url 'listaclientes' %}">Volver</a>
            </div>
            </div>
        </div>
    </div>
    
    {% endblock %}

</body>
</html>

Appventas/templates/appventas/clientesdetalle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle de Cliente</title>
</head>
<body>

    {% extends "appventas/padre.html" %}

    {% load static %}

    {% block contenidoQueCambia %}

    <div class="container px-lg-5">
        <div class="p-2 p-lg-3 bg-light rounded-3 text-center">
            <div class="m-2 m-lg-3">

                <h3>Usted está en la sección de clientes</h3>
                <h5>Detalle de Cliente</h5>
                <div style="text-align: left;">
                <p>Nombre: <i>{{object.nombre}}</i></p>
                <p>Apellido: <i>{{object.apellido}}</i></p>
                <p>Dirección: <i>{{object.direccion}}</i></p>
                <p>E-mail: <i>{{object.email}}</i></p>            
                
                <a href="{% url 'listaclientes' %}">Volver</a>
            </div>
            </div>
        </div>
    </div>
    
    {% endblock %}

</body>
</html>

Appventas/templates/appventas/clientesedit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Cliente</title>
</head>
<body>

    {% extends "appventas/padre.html" %}

    {% load static %}

    {% block contenidoQueCambia %}

    <div class="container px-lg-5">
        <div class="p-2 p-lg-3 bg-light rounded-3 text-center">
            <div class="m-2 m-lg-3">

                <h3>Usted está en la sección de clientes</h3>
                <h5>Editar Cliente</h5>
                <div style="text-align: left;">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}

                    <input type="submit" value="Guardar">

                </form>          
                
                <a href="{% url 'listaclientes' %}">Volver</a>
            </div>
            </div>
        </div>
    </div>
        
    {% endblock %}

</body>
</html>

Appventas/templates/appventas/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Heroic Features - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'appventas/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home u.u</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About!</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact?</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="py-5">
            <div class="container px-lg-5">
                <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
                    <div class="m-4 m-lg-5">
                        <h1 class="display-5 fw-bold">A warm welcome!</h1>
                        <p class="fs-4">Bootstrap utility classes are used to create this jumbotron since the old component has been removed from the framework. Why create custom CSS when you can use utilities?</p>
                        <a class="btn btn-primary btn-lg" href="#!">Call to action</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- Page Content-->
        <section class="pt-4">
            <div class="container px-lg-5">
                <!-- Page Features-->
                <div class="row gx-lg-5">
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-collection"></i></div>
                                <h2 class="fs-4 fw-bold">Fresh new layout</h2>
                                <p class="mb-0">With Bootstrap 5, we've created a fresh new layout for this template!</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-cloud-download"></i></div>
                                <h2 class="fs-4 fw-bold">Free to download</h2>
                                <p class="mb-0">As always, Start Bootstrap has a powerful collectin of free templates.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-card-heading"></i></div>
                                <h2 class="fs-4 fw-bold">Jumbotron hero header</h2>
                                <p class="mb-0">The heroic part of this template is the jumbotron hero header!</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-bootstrap"></i></div>
                                <h2 class="fs-4 fw-bold">Feature boxes</h2>
                                <p class="mb-0">We've created some custom feature boxes using Bootstrap icons!</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-code"></i></div>
                                <h2 class="fs-4 fw-bold">Simple clean code</h2>
                                <p class="mb-0">We keep our dependencies up to date and squash bugs as they come!</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-patch-check"></i></div>
                                <h2 class="fs-4 fw-bold">A name you trust</h2>
                                <p class="mb-0">Start Bootstrap has been the leader in free Bootstrap templates since 2013!</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

Appventas/templates/appventas/padre.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}Bienvenido{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'appventas/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <a class="navbar-brand" href="{% url 'inicio' %}">Web S.A.</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'about' %}">Acerca de</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {% if user.is_authenticated %}
                                    Hola, {{ user.username }}
                                {% else %}
                                    Usuario
                                {% endif %}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% if user.is_authenticated %}
                                    <li><a class="dropdown-item" href="{% url 'edit_profile' %}">Editar Perfil</a></li>
                                    <li><a class="dropdown-item" href="{% url 'password_change' %}">Cambiar contraseña</a></li>
                                    <li><a class="dropdown-item" href="{% url 'Logout' %}">Logout</a></li>
                                {% else %}
                                    <li><a class="dropdown-item" href="{% url 'Login' %}">Login</a></li>
                                    <li><a class="dropdown-item" href="{% url 'Register' %}">Registrarse</a></li>
                                    
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="py-3">
            <div class="container px-lg-5">
                <div class="p-1 p-lg-2 bg-light rounded-3 text-center">
                    <div class="m-1 m-lg-2">
                        <h1 class="custom-heading">Bienvenido a nuestro sitio web!</h1>
                        <p class="custom-paragraph">Seleccione a continuación la sección deseada</p>
                        <a class="btn btn-primary custom-button" href="{% url 'listaclientes' %}">Clientes</a>
                        <a class="btn btn-primary custom-button" href="{% url 'listaproductos' %}">Productos</a>
                        <a class="btn btn-primary custom-button" href="{% url 'listaservicios' %}">Servicios</a>
                    </div>
                </div>
            </div>
        </header>

        {% block contenidoQueCambia %}
        <div class="container px-lg-5">
            <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
                <div class="m-4 m-lg-5">
                    Gracias por su interés en nuestra web
                    <h1 class="display-5 fw-bold">*</h1>
                </div>
            </div>
        </div>
        {% endblock %}

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Lucas Franchina - 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

Appventas/templates/appventas/productos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Productos</title>
</head>
<body>

    {% extends "appventas/padre.html" %}

    {% load static %}

    {% block contenidoQueCambia %}

    <div class="container px-lg-5">
        <div class="p-2 p-lg-3 bg-light rounded-3 text-center">
            <div class="m-2 m-lg-3">

                <h3>Usted está en la sección de productos</h3>
                <a href="{% url 'nuevoproducto' %}">Nuevo Producto</a>
                <div style="text-align: left;">
                {% for producto in productos_list %}
            
                <li>{{producto.producto}}, {{producto.marca}}</li>
                <a href="{% url 'productosdetalle' producto.pk %}">Ver</a> <a href="{% url 'productoseditar' producto.pk %}">Editar</a> <a href="{% url 'productosborrar' producto.pk %}">Borrar</a>
                {% endfor %}
            </div>
            </div>
        </div>
    </div>
    
    {% endblock %}

</body>
</html>

Appventas/templates/appventas/productosdelete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Borrar Producto</title>
</head>
<body>

    {% extends "appventas/padre.html" %}

    {% load static %}

    {% block contenidoQueCambia %}

    <div class="container px-lg-5">
        <div class="p-2 p-lg-3 bg-light rounded-3 text-center">
            <div class="m-2 m-lg-3">

                <h3>Usted está en la sección de productos</h3>
                <h5>Borrar Producto</h5>
                <div style="text-align: left;">
                <form action="" method="POST">
                    {% csrf_token %}
                    Está seguro que desea borrar el producto {{object.producto}} {{object.marca}}?
                    
                    <input type="submit" value="Si, eliminar">

                </form>          
                
                <a href="{% url 'listaproductos' %}">Volver</a>
            </div>
            </div>
        </div>
    </div>
    
    {% endblock %}

</body>
</html>

Appventas/templates/appventas/productosedit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Producto</title>
</head>
<body>

    {% extends "appventas/padre.html" %}

    {% load static %}

    {% block contenidoQueCambia %}

    <div class="container px-lg-5">
        <div class="p-2 p-lg-3 bg-light rounded-3 text-center">
            <div class="m-2 m-lg-3">

                <h3>Usted está en la sección de productos</h3>
                <h5>Editar Producto</h5>
                <div style="text-align: left;">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}

                    <input type="submit" value="Guardar">

                </form>          
                
                <a href="{% url 'listaproductos' %}">Volver</a>
            </div>
            </div>
        </div>
    </div>
        
    {% endblock %}

</body>
</html>

Appventas/templates/appventas/servicios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Servicios</title>
</head>
<body>

    {% extends "appventas/padre.html" %}

    {% load static %}

    {% block contenidoQueCambia %}

    <div class="container px-lg-5">
        <div class="p-2 p-lg-3 bg-light rounded-3 text-center">
            <div class="m-2 m-lg-3">

                <h3>Usted está en la sección de servicios</h3>
                <a href="{% url 'nuevoservicio' %}">Nuevo Servicio</a>
                <div style="text-align: left;">
                {% for servicio in servicios_list %}
            
                <li>{{servicio.servicio}}, {{servicio.proveedor}}</li>
                <a href="{% url 'serviciosdetalle' servicio.pk %}">Ver</a> <a href="{% url 'servicioseditar' servicio.pk %}">Editar</a> <a href="{% url 'serviciosborrar' servicio.pk %}">Borrar</a>
                {% endfor %}
            </div>
            </div>
        </div>
    </div>
    
    {% endblock %}

</body>
</html>